version: "3.0"
services:
  redis:
    image: redis:5.0.4
    ports:
      - "6379:6379"

  fam100:
    build: .
    command: /fam100 -quorum 3
    depends_on:
      - redis
    volumes:
      - "./qna:/qna"
    environment:
      TELEGRAM_KEY: "6746471345:AAFPIDRGMS116mbveDiN9NgzjcbA23Dcxkw}"
      QUESTION_DB_PATH: "qna/questions.txt"
      REDIS_ADDR: "redis:6379"

